import React from 'react';
import Navbar from './components/Navbar';
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div>
        <Navbar/>
          <h1>Confident Voices !</h1>
        </div>
        {children}
      </body>
    </html>
  )
}
