export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div>
          <h1>Hello, Next.js!</h1>
          <p>Welcome to my Next.js application.</p>
        </div>
        {children}
      </body>
    </html>
  )
}
